### ISSUE TITLE
Feedback from Hookah

### ISSUE THREAD

**Issue by hcqpham** [niccalle/cogs121#2]
The bike path, open source, and dog sitting storyboards were interesting! 

You could definitely expand on the bike path storyboard to make it encompass any type of road instead of just bike paths. That would expand your user base. You had a lot of interesting ideas but we would recommend trying to find something more creative or more unique, because some of the storyboards were more general and similar products could be found on Google Play / iOS app store.

**Comment by kandarpksk** [comment]
@hcqpham Please move this to the original thread and close the issue.
